version: '3.8'

services:
  chatterbox-tts:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: chatterbox-tts-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/cache/huggingface
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - TORCH_HOME=/app/cache/torch
    volumes:
      # Persist generated audio outputs
      - ./outputs:/app/outputs
      # Persist model cache to avoid re-downloading
      - ./cache:/app/cache
      # Optional: Mount custom voices directory
      - ./voices:/app/voices:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

# Optional: For development with live code updates
  chatterbox-tts-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: chatterbox-tts-dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/cache/huggingface
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - TORCH_HOME=/app/cache/torch
    volumes:
      # Mount source code for development
      - .:/app
      # Persist outputs and cache
      - ./outputs:/app/outputs
      - ./cache:/app/cache
    restart: "no"
    profiles:
      - dev

volumes:
  outputs:
  cache: 